### ISSUE TITLE
Used Memory ramps up and resets causing massive lag

### ISSUE THREAD

**Issue by HyperTec** [jadedcat/AS2Configs#94] opened 2015-08-31 07:57 UTC
I've been playing this mod pack (Agrarian Skys 2 now 1.1.13) for a few weeks and the lag has rendered the game almost unplayable. When I hit F3 I notice the ssed memory, in the top right, keeps going up and resetting nonstop. It gets to about 40 or 50 percent and drops back down and ramps up again, over and over again. It says there are major fluctuations in FPS (from 30 to 72 to 48 to 37 etc...)  but it all looks like its at about 5 FPS. I checked my java version and its up to date at 1.8.0_60 64-bit. But then I noticed that the Cursed launcher forces 1.8.0_25 64-bit. I don't know what the problem could be. oh, also, it happens even if open a completely unused map. I have 4 gigs of ram set from the cursed laucher and I havent changed any of the java arguments. Please help!

![2015-08-31_00 44 07](https://cloud.githubusercontent.com/assets/14050371/9574432/b51b384a-4f7b-11e5-8be4-75fc0f2d75ae.png)

**Comment by pjfranke** [comment] 2015-09-01 17:31
> When I hit F3 I notice the ssed memory, in the top right, keeps going up and resetting nonstop. It gets to about 40 or 50 percent and drops back down and ramps up again, over and over again.

That is normal behavior in a game that has stuff running automatically.  Even without automated machines, it's still normal behavior for mob spawning and movement, though I expect it would be slower.

Run "/cofh tps" to see if your TPS is low, or normal. It shouldn't be lower than 20, otherwise that's indicating you are having issues.

You may want to add Opis to your pack, and launch the profiler to see what the issue is.

The Java version is correct; CurseVoice includes it's own Java version to ensure consistency between packs, ease troubleshooting, and avoiding issues with system Java.

How much system RAM do you have?  4GB for the game is actually a bit high, unless you are running an HD texture pack.  For no texture pack (or normal resolution ones), I have had great success with 3GB for all packs I play, even when playing on a 16GB computer.

**Comment by MarshMilo100** [comment] 2015-09-06 14:12
closing due to inactitvy

**Closed by MarshMilo100** 2015-09-06 14:12 UTC
Labels: user error, wontfix
