### ISSUE TITLE
Game won't startup

### ISSUE THREAD

**Issue by Tyronk1** [jadedcat/AS2Configs#203] opened 2016-01-20 07:56 UTC
I have been looking for fixes for this but cannot find anything, it seems to be common error for many people, upon launching the game we get this error:

![ag2](https://cloud.githubusercontent.com/assets/16793513/12442830/00472e28-bf5c-11e5-8a41-9438b78492d4.jpg)

Java has been updated, so don't think it's that, Please could someone help with a fix in order to get the game running, thanks!

**Comment by Trisscar05** [comment] 2016-01-23 05:14
Have you done the usual checklist, involving backing up and un/reinstalling everything?(Don't do this with Java till last if you really even have to, it takes forever.)

**Comment by MaLoe** [comment] 2016-01-23 13:29
I had exactly the same error. Fixed by deleting …/Curse/Minecraft folder and installing AS2 again. What also worked, was to select an older forge version.

**Comment by Tyronk1** [comment] 2016-01-26 15:10
Have tried reinstalling but not deleting /Curse/Minecraft folder as stated above, will give that a go and report back

**Comment by samuelroy21** [comment] 2016-01-28 04:34
in the future please copy paste the text into a pastebin, makes i easier to skim through

**Comment by cblair91** [comment] 2016-01-28 14:17
@Tyronk1 Have you installed 32 bit java alongside 64 bit?

**Comment by jikuja** [comment] 2016-01-28 17:30
This is caused by bad forge installation: Java cannot open forge-xxxx.jar and classloader fails to find class FMLTweaker.  Something(blame antivirus application) blocked when forge jar was being writed into disk and caused CV to save broken jar file OR somthing blocks when file read by classloader. 

I earlier asked in #curseforge@esper how to trigger forge reinstallation. Did not get answer(s). Probably best fixes are

- Reinstall pack(s). Not sure if reinstalling pack triggers hash check for libraries. Maybe or maybe not.
- Delete forge file from Curse\Minecraft\libraries\net\minecraftforge\forge\<insert version here>\
- Check logs and settings of antivirus applications. Whitelist CV's directories if needed. (Maybe user should run AV manually after pack installation?)

**Comment by yogibear79** [comment] 2016-02-16 22:26
Had the same trouble. Funny thing was that the AS2 Version 1.1.13 runs perfect. When I switch to 1.1.14 it stops in the Launcher with the same error message as yours. Figured out that 1.1.14 runs on forge 10.13.4.1492 and the 1.1.13 runs on forge 10.13.4.1469. So when Curse started the  Minecraft Launcher I went into "Edit Profile". There I changed the forge Version to 10.13.4.1469 and then it worked.

**Comment by jikuja** [comment] 2016-02-17 06:29
Well there is simple explanation for that behaviour. Jar for forge 1492 is broken in your disk but jar for 1469 is ok. That is the reason why changing forge version fixes problem. Real fixes are still missing from CV.

**Comment by tecrogue** [comment] 2016-03-29 07:57
Duplicate of #189

**Comment by Developaws** [comment] 2016-08-01 23:39
Corrupted forge installation;

1. Write down minecraft version(we need forge version later) pack uses
2. Click `(...)` button
3. Select `Open Folder`
4. Locate `Curse/Minecraft`
4. Open `install/libraries/net/minecraftforge/forge/<version from step 1>´
5. Delete file in the folder. e.g. `forge-1.10-12.18.0.2000-1.10.0.jar`
6. Restart pack

**Closed by Developaws** 2016-08-01 23:39 UTC
Labels: duplicate, help wanted
