### ISSUE TITLE
AS2 nei crash

### ISSUE THREAD

**Issue by freacko00** [jadedcat/AS2Configs#240] opened 2016-04-07 22:10 UTC
When ever i play with a friend of mine, LAN, him hosting, I crash when i try to look up any of the agricraft seed mutations, but he can view them fine
[crash-2016-04-07_17.08.12-client.txt](https://github.com/jadedcat/AS2Configs/files/209314/crash-2016-04-07_17.08.12-client.txt)

**Comment by Trisscar05** [comment] 2016-04-08 03:04
Already been at least noted in another thread, though I'm at a loss as to where. Anyone remember the last time this issue was posted and where it is now?

**Comment by Developaws** [comment] 2016-08-01 23:47
Duplicate of #148

**Closed by Developaws** 2016-08-01 23:47 UTC
Labels: unconfirmed
