### ISSUE TITLE
Backup level.dat is being used

### ISSUE THREAD

**Issue by FRAPzVENOMz** [jadedcat/AS2Configs#218] opened 2016-02-15 19:00 UTC
The game is telling me that i need to backup my save, and i am currently needing help to back my save up so that i dont lose my progress

**Comment by Trisscar05** [comment] 2016-02-15 19:43
....What? Could we get screenshots and a crash log via pastebin? Also a more detailed post? XD

**Comment by FRAPzVENOMz** [comment] 2016-02-15 19:58
![image](https://cloud.githubusercontent.com/assets/17257475/13058911/6ed5587a-d41e-11e5-9782-2b6f2088db89.png)

**Comment by FRAPzVENOMz** [comment] 2016-02-15 19:59
If i press yes, my game crashes, if i click no, it takes me back to the main menu, im trying to play my singleplayer world

**Comment by Trisscar05** [comment] 2016-02-15 21:57
Mk. So the first thing I'd suggest is to disable AromaBackup by going to "edit modpack" in the launcher while you have Ag Skies 2 selected, assuming you're using FTB. Then attempt to reload the game and see what happens.
If it crashes yet again, try to make sure the console is set to "Show", then use one of the buttons on it to post it's contents to pastebin, submit that, then post the link to said pastebin file here.

**Comment by FRAPzVENOMz** [comment] 2016-02-16 01:38
Im using Curse to play agrarian skies 2

**Comment by FRAPzVENOMz** [comment] 2016-02-16 02:04
---- Minecraft Crash Report ----
The pack has been tampered with. Do not report any errors.
 AromaBackup, origin, thaumicexpansion

// But it works on my machine.

Time: 16/02/16 02:03
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at hardcorequesting.QuestingData.<init>(QuestingData.java:518)
	at hardcorequesting.QuestingData.readAllData(QuestingData.java:477)
	at hardcorequesting.QuestingData$1.read(QuestingData.java:403)
	at hardcorequesting.network.FileHelper.loadData(FileHelper.java:107)
	at hardcorequesting.QuestingData.load(QuestingData.java:432)
	at hardcorequesting.WorldEventListener.onLoad(WorldEventListener.java:23)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_698_WorldEventListener_onLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Trisscar05** [comment] 2016-02-16 05:57
....Huh. Interesting. like I said, disable AromaBackup and see if that skips the problematic loop.
But this also indicates that something went wrong with Hardcore Questing. I don't have quite as much experience with the mod, so question to any lurkers: How do you clear questing data outside of the game?

**Comment by FRAPzVENOMz** [comment] 2016-02-16 13:33
ive disabled AromaBackup and it still causes it to do the above....

**Comment by Trisscar05** [comment] 2016-02-17 01:43
Mk, so from the FTB Gamepedia entry on HCQ:
-To test everything again from scratch, exit Minecraft, go to your Minecraft folder, and locate \saves\YOUR WORLD NAME\HardcoreQuesting . Inside should be two files - players.dat and players.dat-backup . Make a backup of these somewhere just to be safe, and then delete both files. Now start up Minecraft again and you should have a nice clean HQM quest book, with all of your quests in place but none of the completion tasks done.
Try this and see if it fixes things? Make sure to backup your world though, so if it is the quests we can figure out which ones later.

**Comment by tecrogue** [comment] 2016-03-29 08:11
Duplicate of issue #195

**Comment by Developaws** [comment] 2016-08-01 23:37
Corrupted world, only fix is to delete, or restore from backup.

As no response in more than a month, closing.

**Closed by Developaws** 2016-08-01 23:37 UTC
Labels: duplicate
