### ISSUE TITLE
Cooking Table Crash

### ISSUE THREAD

**Issue by Rosencorpse** [jadedcat/AS2Configs#141] opened 2015-10-13 04:54 UTC
Right after I looked at stock made out of pumpkins in the cooking table, went to the fridge got a pumpkin and made it, I came back to open the cooking table and crash. Every time I open it, it gives me a fatal error message and takes me to the server screen, which is funny cuz i'm not playing on a server. Anyway, even after moving the table around, and moving stuff out of the fridge, I still can't open it without getting a fatal error message and boot.

**Comment by Rosencorpse** [comment] 2015-10-13 05:15
I was able to recreate the crash with both of the save files I have from before the update today, but the new worlds I make don't have the crash. It appears the crash comes from the no available recipes screen on the cooking table, but only happens on save files created before the update today. It's only the kitchen table, but would you recommend me making a new game?

**Comment by Aessilva** [comment] 2015-11-12 10:03
This happens to me as well. I use the back up and wind it back to the last saved point. All it does is shut down and say a fatal error has occurred. You have been disconnected. Then it boots you to the multi player screen even if your not open to lan and only playing single player. I have had to wind back my single player about 3 times now due to the stove not working after I open the fridge.

**Comment by Trisscar05** [comment] 2015-11-14 05:33
I'd suggest, if the placed kitchen stuff is still giving you trouble, that you go into MCEdit or similar and delete the offending blocks. At the very least it will mean you don't have to start over.

**Comment by cblair91** [comment] 2015-12-19 08:58
@Rosencorpse Is this still occurring?

**Comment by Virkkoka** [comment] 2016-01-06 02:10
This issue is still occurring in v1.1.13.  It occurs when opening the Cooking Table with a seed in your inventory. Twich Highlight of it happening including it not happening beforehand: http://www.twitch.tv/virkkoka/v/33828088

**Comment by Developaws** [comment] 2016-08-01 23:48
Possible duplicate of #166, but also might be a different bug with the same mod?

**Comment by Developaws** [comment] 2017-06-18 18:20
This issue was moved to JadedPacks/AS2Configs#3

**Closed by Developaws** 2017-06-18 18:20 UTC
Labels: accepted, bug
