### ISSUE TITLE
1.1.14 recipe problem 

### ISSUE THREAD

**Issue by die4uece** [jadedcat/AS2Configs#172] opened 2015-11-17 11:05 UTC
i've downloaded 1.1.14 recently and in skyfarm quest line when we create agricraft stuff, theres bedrock requirement instead a sprinkler i suppose ... so can it be fixed somehow ?

**Comment by MarshMilo100** [comment] 2015-11-17 14:10
First off: screenshot plz.

Next: in hqm if an item Id changes or metadata changes, then the item gets replaced with bedrock in the quest book, whereas previously it would crash the game because of the id mismatch.

Lastly: this will hopefully be fixed in the next update.

Quick fix: if you spawn in the op book, you can force completion of the quest and just void a sprinkler, then claim the rewards.

**Comment by pjfranke** [comment] 2015-12-14 06:11
Confirmed, the sprinkler ID changed and is now invalid, and one of the quest rewards is invalid as well.

http://puu.sh/lUTYd/8a38e4f192.jpg

Will be fixed in upcoming version, or in AS2 re-release.

**Comment by samuelroy21** [comment] 2015-12-28 23:59
it appears that my cohorts have addressed your issue the most it can be. As such, I'm closing the thread. But as for you, I give you permission to hack the quest in. type "/HQM edit" into your chat for a debug questbook to do so, provided you made the actual things as well.

**Closed** 2015-12-28 23:59 UTC
Labels: accepted, bug, questbook
