### ISSUE TITLE
Infinite stone glitch with Altar Manipulator and Tesseracts

### ISSUE THREAD

**Issue by Zeroji** [jadedcat/AS2Configs#158] opened 2015-10-27 09:25 UTC
(I'm not sure if it's the right place to post, don't shoot at me)

I was trying to use my Blood Altar through TE's Tesseracts with the Altar Manipulator from Sanguimancy, and I accidentally got my output chest full of stone.

Setup description: one input chest going into the first tesseract via a reinforced servo and an itemduct, the same tesseract put next to the output chest
The second tesseract is placed on top of the Altar Manipulator, and I put a Sanguine Shifter on the Altar Manipulator so it outputs its contents to the tesseract. Both tesseracts are on the same frequency, and set to send/receive items.

I simply put two pieces of stone in the input chest to try, and ended up with stacks of stone everywhere.

Forge: 10.13.4.1492
AS2: 1.1.14

![2015-10-27_10 16 52](https://cloud.githubusercontent.com/assets/15339858/10753912/4c29228e-7c94-11e5-94f9-4579b7fe8996.png)
![2015-10-27_10 17 30](https://cloud.githubusercontent.com/assets/15339858/10753913/4c2c78f8-7c94-11e5-91f5-ba3a9acefe3b.png)

**Comment by samuelroy21** [comment] 2015-11-17 00:18
This could be a UI glitch... try taking the stone out and using it.

**Comment by Zeroji** [comment] 2015-11-17 08:45
Not an UI glitch, I tried that obviously. Any container can be filled with stone, haven't tried with DSUs though but I think it'd be possible to fill one.

**Comment by samuelroy21** [comment] 2015-11-17 14:24
try the system without tesseracts. mebe the tesseracts don't work well with the sanguimancy items. Also, please share your problem with TeamCOFH and the author(s) of sanguimancy. Hate telling you NOT to use a cool beans tesseract, but tell me if that works for you.

**Comment by pjfranke** [comment] 2015-12-15 03:02
Tested and confirmed.  Likely is a funky issue with using 2 Tesseracts and 1 channel for both input and output, in combination with a block that both inputs and outputs on the same face.

Until this is fixed by TehNutJenkins, I would use 2 more tesseracts on a different channel for in vs out, some other ender transport, or just maybe some piping as a buffer.  If you don't output from the Altar Manipulator directly into the Tesseract, but instead to a different side, and use ducts and a servo (or something else) to pull out and push them into the tesseract, you won't have this issue.

Tesseracts effectively present the face connected to the far end, to the end connected to a block.  There's zero inventory space, they just magically connect what connects to them.  The issue is unlikely to be caused by the Tesseracts, even if they're one of the few blocks that you'd be able to duplicate the issue with.

**Comment by Developaws** [comment] 2017-06-18 18:21
This issue was moved to JadedPacks/AS2Configs#8

**Closed by Developaws** 2017-06-18 18:21 UTC
Labels: accepted, bug
