### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by Bambam141** [jadedcat/AS2Configs#42] opened 2015-08-12 03:31 UTC
As I put in the title. Upon loading a world I have been playing for a good while now, It crashes before I can even get into the game. I was just playing literally 10 minutes before this crash happened. I can see in the crash log that PackGuard believes that I added ThaumicExpansion and removed BiomeTweaker core. It is very strange because I have never tampered with any of the mods in the pack at all. Anyone with any idea on this issue?

http://pastebin.com/r6JqdtiG

**Comment by MarshMilo100** [comment] 2015-08-12 18:21
Did you update or change/remove mantle? (The core mod for tinkers, natura)

**Comment by Bambam141** [comment] 2015-08-14 03:36
As I mentioned, I haven't touched anything with the pack at all. I have even deleted the pack and reinstalled as well. Maybe I should mention that I don't crash until I actually try to load my world. I have not tried making a new one yet but I won't be able to test that for awhile. Out of town for a week :/

**Comment by MarshMilo100** [comment] 2015-08-18 01:20
what were you doing right before the game crashed?

**Comment by Bambam141** [comment] 2015-08-18 03:59
I was working with Thaumic Energistics I believe. Just breaking down items to essentia for storage. I had to leave home so I saved and quit to title. When I got back and tried to load my save, that's when I got the first crash.

**Comment by thesixler** [comment] 2015-08-18 17:50
I had this problem after I was futzing with a load of storage buses on an ME network. I had to go something like 4 backups deep to get a working save.

Have you tried an older backup? It doesn't explain the problem but it might help you get to playing.

**Comment by Bambam141** [comment] 2015-08-18 20:03
I have not tested backups. I'll be able to check once I am home tomorrow.

I think I'll have to take a look at my config files as well if that really is the case. Though I've never tweaked any of them. Maybe it was a pack update change? Not sure.

**Comment by pjfranke** [comment] 2015-08-18 21:36
The PackGuard message below is our fault; an incorrect config in the 1.1.8 pack version.  The 3 mods mentioned are a part of the pack currently, and were just not added to the PackGuard config as they should have been.

The pack has been tampered with. Do not report any errors.
 origin, thaumicexpansion
 BiomeTweakerCore

Please clarify.  Do you mean that the Minecraft instance crashes while trying to launch the pack, or that your game crashes when trying to load your save?  Are you able to start a new/different save OK?  If there is not a specific mod with an issue we can track down, the only way to fix issues like this is to worldedit out an affected block/item, clear your player inventory/baubles if they are the issue, or to roll back to a backup prior to the issue occuring.

Some issues are caused by invalid files, installs, etc.  Your crashlog does not point to that as the culprit, so likely one of the 3 options above will be the only ways to fix the issue.

**Comment by MarshMilo100** [comment] 2015-08-18 21:38
mcedit not worldedit

**Comment by MarshMilo100** [comment] 2015-08-18 21:39
mcedit is a 3rd party program for editing worlds, while worldedit would do you no good because it is an in game utility, that is useless if you are not able to load the world.

**Comment by Berindei** [comment] 2015-08-18 21:51
The game crashes when I'm trying to load the save. Other saves work just fine.

**Comment by cblair91** [comment] 2015-08-26 14:50
The issue is caused by mantle attempting to track an entity that appears to have too many data values attached to it (weird?). This is obviously an issue with mantle tracking, that I have had issues with before. The best action is to report it to mantle, and see their response regarding it.

**Comment by cblair91** [comment] 2015-08-26 14:56
Also, a possible fix, but recommended to take a back-up before doing so...
In configs/forge.cfg, change "B:removeErroringEntities=false" to "B:removeErroringEntities=true", start your server, login. Once logged in, and it not crashing, stop the server and change the config back to false. Then play again like normal :)

**Comment by DoNotWardBaron** [comment] 2015-08-29 16:01
How can I tell which blocks/items are affecting the save and causing me to crash? as I have the same problem.

**Comment by pjfranke** [comment] 2015-08-31 02:56
@DoNotWardBaron If you are having issues, please open a new issue, and attach your Forge crash log.  Ideally put the crashlog on pastebin, and link it here so we don't have to scroll so much every time we look at the issue/add comments. :)

**Comment by pjfranke** [comment] 2015-08-31 02:58
Original poster hasn't updated in 12 days, closing.

**Closed by pjfranke** 2015-08-31 02:58 UTC
Labels: unconfirmed
